stages:
  - build-deploy

build-deploy:
  stage: build-deploy
  tags:
    - development
  before_script:
    - echo "@adameds:registry=https://gitlab.com/api/v4/groups/93029767/-/packages/npm/" >> .npmrc
    - echo "//gitlab.com/api/v4/groups/93029767/-/packages/npm/:_authToken=$AUTH_TOKEN" >> .npmrc
  script:
    - docker compose --env-file /home/env/.env.setting up --build -d
  only:
    - dev-deployment

build-prod:
  stage: build-deploy
  tags:
    - prod-runner
  before_script:
    - echo "@adameds:registry=https://gitlab.com/api/v4/groups/93029767/-/packages/npm/" >> .npmrc
    - echo "//gitlab.com/api/v4/groups/93029767/-/packages/npm/:_authToken=$AUTH_TOKEN" >> .npmrc
  only:
    - prod-deployment
  script:
    - docker compose -f prod-compose.yml --env-file /home/gitlab-runner/adameds/.env.setting up --build -d
