stages:
  - build-deploy

build-deploy:
  stage: build-deploy
  tags:
    - local-dev
    - local
  before_script:
    - docker compose --env-file /home/engineer/adameds/.env.setting down --rmi all
    - echo "@adameds:registry=https://gitlab.com/api/v4/groups/93029767/-/packages/npm/" >> .npmrc
    - echo "//gitlab.com/api/v4/groups/93029767/-/packages/npm/:_authToken=$AUTH_TOKEN" >> .npmrc
  script:
    - docker compose --env-file /home/engineer/adameds/.env.setting up -d
  only:
    - dev-deployment

build-prod:
  stage: build-deploy
  tags:
    - prod-runner
  before_script:
    - echo "@adameds:registry=https://gitlab.com/api/v4/groups/93029767/-/packages/npm/" >> .npmrc
    - echo "//gitlab.com/api/v4/groups/93029767/-/packages/npm/:_authToken=$AUTH_TOKEN" >> .npmrc
    - docker compose -f prod-compose.yml --env-file /home/gitlab-runner/adameds/.env.setting down --rmi all
  only:
    - prod-deployment
  script:
    - docker compose -f prod-compose.yml --env-file /home/gitlab-runner/adameds/.env.setting up -d
