FROM node:19.5.0-alpine

WORKDIR /adameds-setting
COPY package.json .
ENV DB_NAME=$DB_NAME
ENV DB_HOST=$DB_HOST
ENV DB_USERNAME=$DB_USERNAME
ENV DB_PASSWORD=$DB_PASSWORD
ENV DB_DIALECT=$DB_DIALECT
ENV BASE_URL=$BASE_URL

# API CONFIG
ENV API_BASE=$API_BASE
ENV API_VERSION=$API_VERSION


# Application config
ENV APPLICATION_PORT=8082
ENV APPLICATION_HOST=0.0.0.0

COPY . .
RUN npm install
EXPOSE $APPLICATION_PORT/TCP
CMD ["npm", "run", "start"]
