version: "3.3"
services:
  adaneds-setting:
    container_name: adameds-setting-dev
    image: adameds/setting-service:dev
    ports:
      - 8082:8082
    restart: always
    networks:
      - adameds-network
    environment:
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DIALECT: ${DB_DIALECT}
      BASE_URL: ${BASE_URL}

      # Redis
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_USERNAME: ${REDIS_USERNAME}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_DATABASE: ${REDIS_DATABASE}

      # API CONFIG
      API_BASE: "api"
      API_VERSION: "v3"
    volumes:
      - type: bind
        source: /home/admin/adameds/public.key
        target: /adameds-setting/public.key
      - type: bind
        source: /home/admin/adameds/private.key
        target: /adameds-setting/private.key
networks:
  adameds-network:
    driver: bridge
