services:
  adaneds-setting:
    build:
      context: ./
      dockerfile: Dockerfile
      no_cache: true
    container_name: api-adameds-setting
    image: adameds/setting-service:dev
    ports:
      - 8082:8082
    restart: always
    networks:
      - adameds-network
    environment:
      INFISICAL_TOKEN: ${INFISICAL_TOKEN}
      # API CONFIG
      API_BASE: ${API_BASE}
      API_VERSION: ${API_VERSION}
    # volumes:
    #   - type: bind
    #     source: /home/engineer/adameds/.env.vault
    #     target: /adameds-setting/.env.vault
networks:
  adameds-network:
    driver: bridge
